In [2]:
import pandas as pd
import os

In [3]:
original_metrics = pd.read_csv(os.path.join("..", "og_aeon_summary.csv"))
original_metrics

,dataset,model,seed,n_train,n_test,series_length,n_classes,total_time,peak_memory_mb,accuracy,f1_macro,f1_weighted,status,error_msg,sequence_length
0,ACSF1,aeon_hydra,42,100,100,1460,10,2.239734,581.189632,0.880000,0.880341,0.880341,ok,NaN,NaN
1,Adiac,aeon_hydra,42,390,391,176,37,1.238620,288.620544,0.813299,0.794570,0.798257,ok,NaN,NaN
2,AllGestureWiimoteX,aeon_hydra,42,300,700,500,10,4.898511,1230.585856,0.692857,0.695983,0.695983,ok,NaN,NaN
3,AllGestureWiimoteY,aeon_hydra,42,300,700,500,10,5.172304,2.605056,0.715714,0.713613,0.713613,ok,NaN,NaN
4,AllGestureWiimoteZ,aeon_hydra,42,300,700,500,10,5.264350,3.817472,0.678571,0.674221,0.674221,ok,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,Wine,aeon_hydra,42,57,54,234,2,0.276388,0.049152,0.888889,0.888889,0.888889,ok,NaN,NaN
124,WordSynonyms,aeon_hydra,42,267,638,270,25,2.740555,81.199104,0.744514,0.615013,0.722019,ok,NaN,NaN
125,Worms,aeon_hydra,42,181,77,900,5,2.045410,82.804736,0.740260,0.720916,0.729533,ok,NaN,NaN
126,WormsTwoClass,aeon_hydra,42,181,77,900,2,2.032044,0.032768,0.766234,0.762996,0.766953,ok,NaN,NaN
127,Yoga,aeon_hydra,42,300,3000,426,2,14.020799,1050.820608,0.932667,0.932275,0.932643,ok,NaN,NaN

In [4]:
optimised_metrics = pd.read_csv(os.path.join("..", "optimised_aeon_summary.csv"))
optimised_metrics

,dataset,model,seed,n_train,n_test,series_length,n_classes,total_time,peak_memory_mb,accuracy,f1_macro,f1_weighted,status,error_msg,sequence_length
0,ACSF1,aeon_hydra,42,100,100,1460,10,1.162846,61.915136,0.880000,0.880341,0.880341,ok,NaN,NaN
1,Adiac,aeon_hydra,42,390,391,176,37,1.345779,138.756096,0.813299,0.794570,0.798257,ok,NaN,NaN
2,AllGestureWiimoteX,aeon_hydra,42,300,700,500,10,1.823071,133.169152,0.690000,0.692623,0.692623,ok,NaN,NaN
3,AllGestureWiimoteY,aeon_hydra,42,300,700,500,10,1.795739,1.359872,0.711429,0.708833,0.708833,ok,NaN,NaN
4,AllGestureWiimoteZ,aeon_hydra,42,300,700,500,10,1.796775,4.161536,0.678571,0.674246,0.674246,ok,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,Wine,aeon_hydra,42,57,54,234,2,0.240321,2.342912,0.888889,0.888889,0.888889,ok,NaN,NaN
124,WordSynonyms,aeon_hydra,42,267,638,270,25,2.608850,31.375360,0.744514,0.615013,0.722019,ok,NaN,NaN
125,Worms,aeon_hydra,42,181,77,900,5,0.855529,17.055744,0.740260,0.720916,0.729533,ok,NaN,NaN
126,WormsTwoClass,aeon_hydra,42,181,77,900,2,0.856433,0.032768,0.766234,0.762996,0.766953,ok,NaN,NaN
127,Yoga,aeon_hydra,42,300,3000,426,2,4.876667,-0.065536,0.932667,0.932275,0.932643,ok,NaN,NaN

In [7]:
original_metrics[["total_time", "accuracy"]].describe()

       total_time    accuracy
count  128.000000  128.000000
mean     9.411633    0.848360
std     38.763925    0.149701
min      0.039449    0.324367
25%      0.599594    0.766558
50%      1.632669    0.892356
75%      6.777848    0.969003
max    432.228235    1.000000

In [9]:
optimised_metrics[["total_time", "accuracy"]].describe()

       total_time    accuracy
count  128.000000  128.000000
mean     3.124716    0.848006
std      4.764253    0.150081
min      0.037085    0.324367
25%      0.429451    0.766558
50%      1.026530    0.892356
75%      3.517861    0.968619
max     30.928476    1.000000